export const ADD_CONTACT = "ADD_CONTACT"
export const REMOVE_CONTACT = "REMOVE_CONTACT"
export const LOCALSTORAGE_GET = "LOCALSTORAGE_GET"
export const LOCALSTORAGE_SET = "LOCALSTORAGE_SET"
export const SEARCH_INPUT = "SEARCH_INPUT"






